### ISSUE TITLE
你好，如何解决由于非正常游戏环境而结束战斗

### ISSUE THREAD

**Issue by sayainchina** [cs8425/SDGO-server#2]
你好，如何解决由于非正常游戏环境而结束战斗
![GOnlineScreenShot_20190607_153917](https://user-images.githubusercontent.com/33513771/63573168-2b02e900-c574-11e9-9774-400c687dc1c0.jpg)
谢谢

**Comment by cs8425** [comment]
抱歉
那是客戶端的問題
無關單機服程式
