### ISSUE TITLE
do you know how to change this code to connect with DB

### ISSUE THREAD

**Issue by stank2010** [cs8425/SDGO-server#3]
I don't know what is process of each packet ,Can you change this.

**Comment by cs8425** [comment]
Connect to DB for accessing what data?
If you means `robot.txt` and `egg.txt`, they can be easily saved into DB.
Just modify `parseConfig.go`, and you can do what you want.

**Comment by stank2010** [comment]
Thank you. 
and if I want to open LAN server and make my own user and friend user , Could you guide me how to change your own code.

**Comment by cs8425** [comment]
I'm not sure what type of LAN server you want.
For 'Practice mode', you can modify following line for different grids for each user connection:
https://github.com/cs8425/SDGO-server/blob/master/server.go#L101-L103
Or just let other user connect to the server by IP & port.

But If you means PvP/PvE mode, I'm afraid that I can't help you too much.
We still missing lots of data and need lots of work for building a playable multiplayer server.
